import Head from "next/head";

export default function TermsPage() {
  return (
    <>
      {/* 🔹 SEO + Open Graph + Twitter Meta Tags */}
      <Head>
        <title>Terms & Conditions | CViEx</title>
        <meta
          name="description"
          content="Read the official Terms and Conditions of CViEx. Learn about user responsibilities, data handling, and AI-generated content policies."
        />
        <meta
          name="keywords"
          content="terms and conditions, CViEx, resume builder, policies, legal"
        />
        <meta name="author" content="CViEx" />

        {/* Open Graph */}
        <meta property="og:title" content="Terms & Conditions | CViEx" />
        <meta
          property="og:description"
          content="Understand the rules and policies of using CViEx’s AI-powered resume platform."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://cviex.com/terms" />
        <meta property="og:image" content="https://cviex.com/og-image.png" />

        {/* Twitter Card */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Terms & Conditions | CViEx" />
        <meta
          name="twitter:description"
          content="Understand how CViEx manages your data and responsibilities with AI-powered resume building."
        />
        <meta name="twitter:image" content="https://cviex.com/og-image.png" />
      </Head>

      {/* 🔹 Terms Content */}
      <main className="max-w-4xl mx-auto py-16 px-6 text-gray-800">
        <h1 className="text-4xl font-bold text-center text-primary mb-8">
          Terms & Conditions
        </h1>

        <p className="text-lg text-center mb-10">
          Welcome to <span className="font-semibold">CViEx</span>. By accessing
          or using our platform, you agree to comply with the following Terms
          and Conditions. Please read them carefully.
        </p>

        {/* Sections */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">1. Data & Privacy</h2>
          <p className="leading-relaxed">
            Your personal data is securely handled and stored in compliance with
            industry best practices. We do not sell or misuse your data, and we
            implement strong security measures to protect your information.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">2. User Responsibility</h2>
          <p className="leading-relaxed">
            You are solely responsible for ensuring the accuracy and truthfulness
            of the information included in your resume. CViEx is not liable for
            any errors, omissions, or consequences resulting from inaccurate
            details provided by you.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            3. AI-Generated Content
          </h2>
          <p className="leading-relaxed">
            Resumes and suggestions generated by our AI are provided as guidance
            only. CViEx does not guarantee job placements, interviews, or hiring
            outcomes based on the generated content.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">4. Limitation of Liability</h2>
          <p className="leading-relaxed">
            CViEx provides its services on an “as-is” and “as available” basis,
            without warranties of any kind. We are not responsible for job
            application results, third-party decisions, or external factors
            affecting your career opportunities.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">5. Updates to Terms</h2>
          <p className="leading-relaxed">
            These Terms may be updated from time to time. Continued use of our
            platform after updates means you accept the revised Terms &
            Conditions. We encourage you to review them periodically.
          </p>
        </section>

        {/* Footer note */}
        <p className="text-sm text-gray-600 text-center mt-12">
          Last updated: October 4, 2025
        </p>
      </main>
    </>
  );
}
