export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto py-12 px-4 h-screen flex justify-center items-center flex-col ">
      <h1 className="text-3xl font-bold mb-4 text-primary">Terms and Conditions</h1>
      <p className="text-base text-black font-semibold leading-relaxed">
        By using MakeResume, you agree to the following terms and conditions:
      </p>
      <ul className="list-disc list-inside mt-4 text-black font-semibold">
        <li>Your data is securely handled and stored with industry best practices.</li>
        <li>MakeResume is not liable for job outcomes based on resumes created.</li>
        <li>You are responsible for the accuracy of the information in your resume.</li>
        <li>Content generated by AI is a suggestion, not a guarantee of success.</li>
        <li>All services are provided “as-is” without warranties.</li>
      </ul>
      <p className="mt-4 text-base text-black font-semibold">
        We may update these terms from time to time. Please review them periodically.
      </p>
    </main>
  );
}
