import Head from "next/head";

export default function TermsPage() {
  return (
    <>
      {/* 🔹 SEO + Open Graph + Twitter Meta Tags */}
      <Head>
        <title>Terms & Conditions | MakeResume</title>
        <meta
          name="description"
          content="Read the Terms and Conditions of MakeResume. Learn how we handle your data, responsibilities, and AI-generated content policies."
        />
        <meta
          name="keywords"
          content="terms and conditions, make resume, ai resume builder, privacy, policies"
        />
        <meta name="author" content="MakeResume" />

        {/* Open Graph */}
        <meta property="og:title" content="Terms & Conditions | MakeResume" />
        <meta
          property="og:description"
          content="Read the Terms and Conditions of MakeResume. Learn how we handle your data, responsibilities, and AI-generated content policies."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://makeresume.com/terms" />
        <meta
          property="og:image"
          content="https://makeresume.com/og-image.png"
        />

        {/* Twitter Card */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Terms & Conditions | MakeResume" />
        <meta
          name="twitter:description"
          content="Understand how MakeResume manages your data and responsibilities with AI-powered resume building."
        />
        <meta
          name="twitter:image"
          content="https://makeresume.com/og-image.png"
        />
      </Head>

      {/* 🔹 Responsive Layout */}
      <main className="max-w-3xl mx-auto py-12 px-6 min-h-screen flex flex-col items-center justify-center text-center">
        <h1 className="text-3xl md:text-4xl font-bold mb-4 text-primary">
          Terms and Conditions
        </h1>

        <p className="text-base md:text-lg text-black font-semibold leading-relaxed">
          By using MakeResume, you agree to the following terms and conditions:
        </p>

        <ul className="list-disc list-inside mt-6 space-y-2 text-black font-semibold text-left">
          <li>
            Your data is securely handled and stored with industry best
            practices.
          </li>
          <li>
            MakeResume is not liable for job outcomes based on resumes created.
          </li>
          <li>
            You are responsible for the accuracy of the information in your
            resume.
          </li>
          <li>
            Content generated by AI is a suggestion, not a guarantee of success.
          </li>
          <li>All services are provided “as-is” without warranties.</li>
        </ul>

        <p className="mt-6 text-base md:text-lg text-black font-semibold">
          We may update these terms from time to time. Please review them
          periodically.
        </p>
      </main>
    </>
  );
}
